# Site settings
title: Brandon Wilcox | Student & Developer
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal Website for Brandon Wilcox
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: brandonkwilcox
github_username: bkwilcox100
instagram_username: brandonkwilcox

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
